apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-dashboard
  namespace: sandbox-dashboard
  labels:
    app.kubernetes.io/name: sandbox-dashboard
    app.kubernetes.io/component: dashboard
